export class BasePath {
    static readonly BASE_URL = "http://localhost:8080/api/v1"
    static readonly AUTH = "auth"
    static readonly ACCOUNT = "accounts"
    static readonly FOLLOW = "follows"
    static readonly BLOG = "blogs"
    static readonly BLOG_TAG = "blog-tags"
    static readonly QUIZ = "quizzes"
    static readonly QUIZ_RESULT = "quiz-results"
    static readonly QUIZ_CATEGORY = "quiz-categories"
    static readonly COMMENT = "comments"
    static readonly NOTIFICATION = "notifications"
    static readonly ROLE = "roles"
    static readonly PERMISSION = "permissions"
    static readonly PERMISSION_GROUP = "permission-groups"
    static readonly REPORT = "reports"
}