export enum ReportType {
    MISLEADING_INFORMATION = "MISLEADING_INFORMATION",
    HATE_SPEECH = "HATE_SPEECH",
    VIOLENT_CONTENT = "VIOLENT_CONTENT",
    INAPPROPRIATE_CONTENT = "INAPPROPRIATE_CONTENT",
    SPAM = "SPAM",
    COPYRIGHT_INFRINGEMENT = "COPYRIGHT_INFRINGEMENT",
    FRAUDULENT_ACTIVITY = "FRAUDULENT_ACTIVITY",
    ILLEGAL_ACTIVITY = "ILLEGAL_ACTIVITY",
    PRIVACY_VIOLATION = "PRIVACY_VIOLATION",
    HARASSMENT = "HARASSMENT",
}